### ISSUE TITLE
generate/sign SBOM attestation files and attach them to container image with cosign

### ISSUE THREAD

**Issue by developer-guy** [kubernetes-sigs/bom#82]
#### What would you like to be added:

Since [Syft v0.40.0](https://github.com/anchore/syft/releases/tag/v0.40.0), Syft can generate and sign SBOM attestations by using cosign. It brings another chance that we can now attach the attestation generated by Syft to a container image.

To get more detail about the development and the concept, follow the links below:

https://github.com/anchore/syft/issues/510
[anchore.com/sbom/creating-sbom-attestations-using-syft-and-sigstore](https://anchore.com/sbom/creating-sbom-attestations-using-syft-and-sigstore/)
[https://github.com/sigstore/cosign/blob/main/specs/ATTESTATION_SPEC.md](https://github.com/sigstore/cosign/blob/main/specs/ATTESTATION_SPEC.md?rgh-link-date=2022-03-21T08%3A48%3A18Z)
[https://github.com/sigstore/cosign/blob/main/doc/cosign_attach_attestation.md](https://github.com/sigstore/cosign/blob/main/doc/cosign_attach_attestation.md?rgh-link-date=2022-03-21T08%3A48%3A18Z)

The same concept can be applied here to the bom tool too.

#### Why is this needed:

To be able to make SBOM generated via the bom tool tamper-proof.

**Comment by puerco** [comment]
I am working on attaching sboms to images, this should be about real soon. I have been also considered adding the sbom inside attestations, but what are the benefits of doing so? I am happy to implement it (or review it if you want to work on that!) but I have not considered working on it yet because I have not yet seen a use case for it.
